[project]
name = "alpha-trade"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "requests>=2.32.4",
    "tabulate>=0.9.0",
    "yfinance>=0.2.65",
]
